project:
  type: website
  output-dir: docs

website:
  title: "Tessa Davis"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - projects.qmd
      - resume.qmd

format:
  html:
    theme: 
      light: quartz
      dark: vapor
    css: styles.css
    toc: true
    page-layout: full

editor: visual

