---
title: "Projects"
format: html
---

Lab 1: Personal Portfolio In lab 1 I worked on creating personal websites through RStudio. This is the website I made for this lab! It was a cool experience and I learned quite a bit in the process. Working with RStudio has quite the learning curve in my experience. I had some problems with correct format in the qmd's to get the website to render as well with getting the site to publish. Once I worked through all the issues I was happy with the results. While completing this lab I learned how to render and publish a website with images, text, and links using RStudio.

Lab 2: Minnesota Tree Growth In Lab 2 I used data on tree growth in Minnesota and focused on using, altering, and understanding data in RStudio. While completing the lab I learned how to filter, slice, arrange, group, and manipulate columns in data. This lab consisted of questions that could be answered using the data. To answer the questions I had to preform tasks like filtering the data to give me answers like how many records there were for a particular tree species. I was also able to learn how to preform tasks like reducing, adding, or renaming columns which was useful.

Lab 5: Final Project - Proposals In lab 5 I wrote two proposals for final project topics for my ESS 330 (Quantitative Reasoning for Ecosystem Science) class. For this lab I went through available data looking for topics I found interesting and could create an RStudio project for. I ended up selecting algal bloom rates in lakes in the U.S. using data from the Cyanobacteria Assessment Network led by NASA, NOAA, USGS, and the U.S. EPA. The second proposal centered around socioeconomic status in relation to exposure of industrially produced air pollution. This project would have used data from the EPA's Enviro site and the CDC to compare pollution related illness rates to proximity to toxin releasing facilities. This lab taught me how to identify data that is useful for different research topics I also learned about adding in Bibtec citations into RStudio.

Lab 7: Final Project - Intro/Methods Draft In lab 7 I worked with my project group to draft the introduction and methods of our final project. The topic we ended up selecting was Karenia brevis (red tide) algal blooms. At this stage we wanted to use data from Alabama, Florida, and Texas. The dataset we used was from NOAA and had information on water quality and presence of red tide. So, we wanted to use this data to see if we could find a model for prediction of red tide based on water conditions. Initially we attempted to have a shared project in RStudio, so we ended up having to use one persons project for submission. This lab taught me loosely about how working on the same RStudio project works and some of the issues it can have. I also learned more on data cleaning with large datasets and about selecting aproptiate models for data analysis.

Lab 9: Final Project - Results/Discussion Draft In lab 9 I worked with my final project group to write the draft of our results and discussion sections of our final report. In this lab I learned about how to find useful information from data sets with missing data. The data we chose for the project had lots of missing data and inconsistencies with site names. We ended up deciding to only use a specific section of Florida and narrowing what conditions we considered. For this lab we also struggled to find the appropriate model for what we wanted the data to tell us. I learned how to run various models like RandomForest, XGBoost, and GLM. I also learned how to determine if a model is sufficient for what you are analyzing. Lastly, I learned how to make categorical data binary in RStudio.

Lab 11: Final Project - Lightning Talks Lab 11 was the final project and presentation for ESS 330. Our final project ended up being on Karenia brevis blooms on Florida's central west coast between certain longitudes and latitudes. We focused on cell count, water temperature, and salinity using GAM to find correlation between these conditions and red tide presence. I learned a whole lot on the impacts red tide has on Florida, what impacts its prevalence, what GAM is and can be used for, and how to determine what a model is telling you and how significant it is.

```         
```
